# 30 numpy exercises



#### 1. Import the numpy package under the name `np` (★☆☆)

In [ ]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [2]:
np.__version__

'1.21.0'

#### 3. Create a null vector of size 10 (★☆☆)

In [3]:
sizes=10
n=np.zeros(sizes)

#### 4. How to find the memory size of any array (★☆☆)

In [4]:
n.size * n.itemsize

80

In [5]:
n.itemsize

8

#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [6]:
print(np.info(np.add))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [7]:
z=np.zeros(10)
z[4]=1
print(z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [8]:
Z=np.arange(10,50,1)
Z

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [9]:
Z[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [10]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [11]:
z=([1,2,0,0,4,0])

In [12]:
print(np.nonzero(z))

(array([0, 1, 4], dtype=int64),)


#### 11. Create a 3x3 identity matrix (★☆☆)

In [13]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 11. Create a 3x3 identity matrix (★☆☆)

In [14]:
np.random.random((3,3,3))

array([[[0.80403562, 0.2142446 , 0.17009524],
        [0.02496755, 0.82927713, 0.50093318],
        [0.63384229, 0.39685768, 0.98665041]],

       [[0.78747379, 0.72876107, 0.57404955],
        [0.06675457, 0.89455616, 0.73798242],
        [0.24559969, 0.66035418, 0.34665584]],

       [[0.09145372, 0.37388976, 0.39353561],
        [0.64607907, 0.91236727, 0.7532551 ],
        [0.4071572 , 0.31766844, 0.95737329]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [15]:
z=np.random.random((10,10))

z

array([[0.7809141 , 0.4440896 , 0.6477798 , 0.32113837, 0.15746726,
        0.23814863, 0.38144336, 0.32368377, 0.1047255 , 0.65448713],
       [0.4532858 , 0.26682405, 0.91168787, 0.12789823, 0.11092148,
        0.96342141, 0.18507662, 0.65749122, 0.70811146, 0.87205413],
       [0.7822007 , 0.72096248, 0.87541474, 0.55618589, 0.05098965,
        0.41962241, 0.51102376, 0.0311096 , 0.89655544, 0.81586314],
       [0.48655235, 0.76510059, 0.94001521, 0.6281679 , 0.58091564,
        0.54262922, 0.65998734, 0.8925438 , 0.26369739, 0.51146235],
       [0.32633828, 0.99750912, 0.41825561, 0.26647325, 0.057337  ,
        0.14453307, 0.74571048, 0.62556811, 0.40123901, 0.41452947],
       [0.81701927, 0.44861269, 0.14020082, 0.88608734, 0.44353407,
        0.73611292, 0.42161007, 0.05460595, 0.49360862, 0.13293089],
       [0.56639607, 0.38541015, 0.47410917, 0.4879889 , 0.95646771,
        0.97546513, 0.83860363, 0.6936185 , 0.41985935, 0.81616868],
       [0.75159172, 0.39702774, 0.9656566

In [16]:
np.max(z)

0.9975091150392151

In [17]:
np.min(z)

0.031109600300544882

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [18]:
z=np.random.random((30))

In [19]:
z

array([0.07703564, 0.07137925, 0.01733373, 0.97684433, 0.28806593,
       0.44317891, 0.14341497, 0.27270319, 0.46914093, 0.76465868,
       0.61157196, 0.2809712 , 0.6011152 , 0.92710647, 0.59876578,
       0.26843998, 0.28881941, 0.7947403 , 0.30196672, 0.24854353,
       0.10066311, 0.47330007, 0.26329689, 0.14744002, 0.24724236,
       0.39929105, 0.70324526, 0.80777304, 0.28262236, 0.82982878])

In [20]:
np.mean(z)

0.4233499681463951

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [21]:
z=np.ones((10,10))

In [22]:
z[1:-1,1:-1] = 0

In [23]:
z

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [24]:
x=np.ones((4,4))
print(x)
x = np.pad(x, pad_width=1, mode='constant', constant_values=0)
print('\n\n' , x)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


 [[0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [25]:
0 * np.nan


nan

In [26]:
np.nan == np.nan


False

In [27]:
np.inf > np.nan


False

In [28]:
np.nan - np.nan


nan

In [29]:
np.nan in set([np.nan])


True

In [30]:
0.3 == 3 * 0.1

False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [31]:
Z=np.diag(1+np.arange(4),k=-1)

In [32]:
Z

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [33]:
Z=np.diag(1+np.arange(4),k=-0)

In [34]:
Z

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [35]:
Z=np.zeros((8,8),dtype=int)
z[1::2 ,::2]=1
z

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [36]:
z[::2, 1::2]=1

In [37]:
z

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0., 1., 1.],
       [1., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0., 1., 1.],
       [1., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0., 1., 1.],
       [1., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0., 1., 1.],
       [1., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [38]:
print (np.unravel_index(100, (6,7,8)))

(1, 5, 4)


In [39]:
print (np.unravel_index(100, (5,7,8)))

(1, 5, 4)


In [40]:
print (np.unravel_index(100, (6,5,8)))

(2, 2, 4)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [41]:
array= np.array([[0,1], [1,0]])
Z = np.tile(array,(4,4))
print (Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [42]:
array= np.array([[0,1], [1,0]])
Z = np.tile(array,(2,2))
print (Z)

[[0 1 0 1]
 [1 0 1 0]
 [0 1 0 1]
 [1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [43]:
z=np.random.random((5,5))
z

array([[0.13889757, 0.45693847, 0.37700131, 0.74981825, 0.77217019],
       [0.33697789, 0.3142051 , 0.37422911, 0.92364578, 0.1516064 ],
       [0.52152277, 0.6664415 , 0.84068507, 0.3254933 , 0.97023925],
       [0.14629872, 0.17693741, 0.59024676, 0.76788705, 0.31703986],
       [0.70422476, 0.09198384, 0.24806083, 0.39390166, 0.59675102]])

In [44]:
zmin, zmax= z.min() ,z.max()
z= (z - zmin)/(zmax-zmin)
print(z)

[[0.05341695 0.41554498 0.32452686 0.74902403 0.77447441]
 [0.27895535 0.25302577 0.32137037 0.9469477  0.06788749]
 [0.48908202 0.65408951 0.8524869  0.26587876 1.        ]
 [0.06184405 0.09672991 0.56733259 0.76959755 0.25625349]
 [0.69711033 0.         0.17771253 0.34376995 0.57473847]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [46]:
color = np.dtype([("r" , np.ubyte ,1),
                ("g" , np.ubyte ,1),
                ("b" , np.ubyte ,1),
                ("a" , np.ubyte ,1)])
color

<ipython-input-46-0a5459b6125a>:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  color = np.dtype([("r" , np.ubyte ,1),


dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [50]:
arr1 = np.arange(1, 16).reshape(5,3)
arr2 = np.arange(1, 7).reshape(3,2)

In [53]:
np.dot(arr1 , arr2)

array([[ 22,  28],
       [ 49,  64],
       [ 76, 100],
       [103, 136],
       [130, 172]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [55]:
z=np.arange(11)
z[(z>3) & (z<8)] *=-1

In [56]:
z


array([ 0,  1,  2,  3, -4, -5, -6, -7,  8,  9, 10])

#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [57]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


In [60]:
sum(range(4))

6

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [67]:
Z



array([[0, 1, 0, 1],
       [1, 0, 1, 0],
       [0, 1, 0, 1],
       [1, 0, 1, 0]])

In [69]:
Z**Z


array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int32)

In [70]:
2 << Z >> 2


array([[0, 1, 0, 1],
       [1, 0, 1, 0],
       [0, 1, 0, 1],
       [1, 0, 1, 0]], dtype=int32)

In [71]:
Z <- Z


array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [72]:
1j*Z


array([[0.+0.j, 0.+1.j, 0.+0.j, 0.+1.j],
       [0.+1.j, 0.+0.j, 0.+1.j, 0.+0.j],
       [0.+0.j, 0.+1.j, 0.+0.j, 0.+1.j],
       [0.+1.j, 0.+0.j, 0.+1.j, 0.+0.j]])

In [73]:
Z/1/1

array([[0., 1., 0., 1.],
       [1., 0., 1., 0.],
       [0., 1., 0., 1.],
       [1., 0., 1., 0.]])

#### 28. What are the result of the following expressions?
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [74]:
np.array(0) / np.array(0)

<ipython-input-74-3585dcb7ab9b>:1: RuntimeWarning: invalid value encountered in true_divide
  np.array(0) / np.array(0)


nan

In [75]:
np.array(0) // np.array(0)

<ipython-input-75-4764261090d0>:1: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)


0

In [76]:
np.array([np.nan]).astype(int).astype(float)

array([-2.14748365e+09])

In [77]:
np.nan

nan

#### 29. How to round away from zero a float array ? (★☆☆)

In [80]:
Z = np.random.uniform(-10,+10,10)
print (np.copysign(np.ceil(np.abs(Z)), Z))

[ 4. -4.  8. -7. -3. -6.  4. -2.  6.  2.]


#### 30. How to find common values between two arrays? (★☆☆)

In [91]:
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,20,10)
print(np.intersect1d(Z1,Z2))

[2 4]


In [92]:
Z1


array([4, 2, 4, 2, 4, 5, 8, 1, 5, 6])

In [93]:
Z2

array([ 9, 13, 16, 16, 19, 11,  2,  4,  4,  4])

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)