# Programs hacker earth with Array and List

## Monk and rotation program

###### Input : 

Input:
The first line will consists of one integer T denoting the number of test cases.
For each test case:
1) The first line consists of two integers N and K, N being the number of elements in the array and K denotes the number of steps of rotation.
2) The next line consists of N space separated integers , denoting the elements of the array A.
Output:
Print the required array.

Constraints:
1<=T <=20






In [10]:
from array import *
def rotation(A,K,N) :
    mid= N-(K%N)
    for i in range(mid, N) :
        print(A[i] , end=" ")
    for j in range(0, mid) :
        print(A[j] , end=" ")
    print("\n")

T=int(input())

for i in range(0, T) :
    N, K= map(int, input().split()) 
    A=list(map(int, input().split()))
    rotation(A,K,N)

1
5 2
1 2 3 4 5
4 5 1 2 3 



##### Monk and Inversions

Input:
First line consists of a single integer T denoting the number of test cases.
First line of each test case consists of one integer denoting N. Following N lines consists of N space separated integers denoting the matrix M.

Output:
Print the answer to each test case in a new line.

In [14]:
T = int(input())

for i in range(0,T) :
    N= int(input())
    matrix=[]
    for j in range(0,N) :
        a=[]
        a.append(list(map(int, input().split())))
        matrix.append(a)
    
print(matrix)

1
3
1 2 3
3 4 5
3 2 5
[[3, 2, 5]]


In [15]:
print(matrix)

[[[1, 2, 3]], [[3, 4, 5]], [[3, 2, 5]]]



### calculate Average temperate and find how many day high temp is above average



In [10]:
numofdays=int(input("Number of days:"))
total=0
arr=[]
for i in range(numofdays):
    nextday=int(input("Days " +str(i+1)+ " high temperature is "))
    arr.append(nextday)
    total +=nextday
average=total/numofdays

# find how many day high temp is above average
count=0
for i in arr :
    if i > average :
        count =count+1
print(count , " number of days is above average temperature")

Number of days:4
Days 1 high temperature is 34
Days 2 high temperature is 56
Days 3 high temperature is 45
Days 4 high temperature is 34
2  number of days is above average temperature


### Missing Number from 1 to 100



In [17]:


def findmissignumber(a,n) :
    sum1=(n+1)*(n+2)/2
    sum2=sum(a)
    print("Missing number is ", int(sum1-sum2))

A=list(map(int, input().split()))
n= len(A)
findmissignumber(A, n)

1 2 3 4 5 6 7 8 9 10 11 12 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
Missing number is  13


### Pair of sum which is equal to target number

In [25]:
def pairSum(arr, s):
    for i in range(len(arr)):
        for j in range(i+1, len(arr)):
            if arr[i]== arr[j] :
                continue
            if arr[i]+arr[j] == s :
                print( arr[i],arr[j])
Target ,N =map(int, input().split())
l=list(map(int, input().split()))
pairSum(l,Target)

6 5
1 2 3 4 5
1 5
2 4


### Finding a number in a array

In [29]:
def finding_a_number(l, s) :
    flag="False"
    for i in l :
        if i==s :
            flag="True"
            break
    return flag
Target ,N =map(int, input().split())
l=list(map(int, input().split()))
print(finding_a_number(l, Target))


    

6 5
1 2 4 6 7 4
True


### Maximum product two integer in a array

In [34]:
def max_product(arr) :
    maxproduct =0
    for i in range(len(arr)) :
        for j in range(i+1, len(arr)) :
            if arr[i]*arr[j]> maxproduct :
                maxproduct = arr[i]*arr[j]
                paris=str(arr[i])+', '+str(arr[j])
    return maxproduct, paris

l=list(map(int, input().split()))
max_prod ,pairs=max_product(l)
print("maximum product is ", max_prod , " for pairs is " + pairs)

1 2 3 55 67 45 78
maximum product is  5226  for pairs is 67, 78


### is the array is unique

In [47]:
def uniquearrayornot(l):
    temp=[]
    for i in l :
        if i in temp :
            print(i)
            return False            
        else :
            temp.append(i)            
    return True
            
            
l=list(map(int, input().split()))

if uniquearrayornot(l) == True :
    print("Array is  Unique and not  has duplicate element")
else :
    print("Array is not  Unique and has duplicate element")
    



1 2 3 12 12 1 2 3
12
Array is not  Unique and has duplicate element


### is two list is permutation to each other

In [3]:
def permutation_of_twolist(l1,l2) :
    if len(l1) != len(l2) :
        return False
    l1.sort()
    l2.sort()
    if l1==l2 :
        return True
    else :
        return False
    
l1=list(map(str, input().split()))
l2=list(map(str, input().split()))
print(permutation_of_twolist(l1,l2))


s h a l i n i
s a n t h o s h
False


### Rotate the 2d matrix 

In [17]:
def rotate(matrix, N) :
    N=len(matrix)
    for layer in range(N//2) :
        first=layer
        last=N-layer-1
        for i in range(first, last) :
            # on top
            top=matrix[layer][i]
            # on bottom left to top left
            matrix[layer][i]=matrix[-i-1][-layer]
            # on right bottom to left bottom
            matrix[-i-1][-layer]=matrix[-layer-1][-i-1]
            # on top right to bottom right
            matrix[-layer-1][-i-1]=matrix[i][-layer-1]
            # on top left to top right
            matrix[i][-layer-1]= top
    return matrix
    
    
import numpy as np
T = int(input())

for i in range(0,T) :
    N= int(input())
    matrix=[]
    a=[]
    for j in range(0,N) :
      
        a.append(list(map(int, input().split())))
        
    matrix=np.array(a)
    print(matrix)
    print(rotate(matrix, N))

1
3
1 2 3
4 5 6
7 8 9
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[7 4 1]
 [8 5 2]
 [9 6 3]]


### middle function , print all element except first and last element

In [23]:
def middle(lst):
    # TODO
    middle=lst[1:-1]
    return middle
myList=list(map(int, input().split()))
middle(myList)

12 3 4 5 67 8 9


[3, 4, 5, 67, 8]

### calculate sum of 2 D array

In [27]:
def sum_of_2d_array(matrix) :
    return sum(sum(matrix))
import numpy as np
N= int(input())
matrix=[]
a=[]
for j in range(0,N) :
    a.append(list(map(int, input().split())))
matrix=np.array(a)
print(sum_of_2d_array(matrix))

3
1 2 3
4 5 6
7 8 9
45


### first and second best score in a list


In [31]:
def bestscore(myList) :
    myList.sort()
    return myList[-1],myList[-2]
myList=list(map(int, input().split()))
first,second=bestscore(myList)
print("The best scores are ", first , second)

12 34 56 78 90 98 97 65 43
The best scores are  98 97


#### Remove the duplicate from the list

In [33]:
def remove_duplicate(myList):
    temp=[]
    for i in myList :
        if i not in temp :           
            temp.append(i)            
    return temp
myList=list(map(int, input().split()))
print(remove_duplicate(myList))

12 34 56 78 90 98 97 65 43 98
[12, 34, 56, 78, 90, 98, 97, 65, 43]
